package com.ARSTM.model;
// Generated 22 oct. 2019 20:11:51 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Absence generated by hbm2java
 */
@Entity
@Table(name = "absence", catalog = "givac_bd")
public class Absence implements java.io.Serializable {

	private int codeAbsence;
	private AnneesScolaire anneesScolaire;
	private Etudiants etudiants;
	private Motif motif;
	private Nature nature;
	private Semestre semestre;
	private SemestreLmd semestreLmd;
	private Date dateSaisie;
	private Date dateAbsence;

	public Absence() {
	}

	public Absence(int codeAbsence, AnneesScolaire anneesScolaire, Etudiants etudiants, Motif motif, Nature nature) {
		this.codeAbsence = codeAbsence;
		this.anneesScolaire = anneesScolaire;
		this.etudiants = etudiants;
		this.motif = motif;
		this.nature = nature;
	}

	public Absence(int codeAbsence, AnneesScolaire anneesScolaire, Etudiants etudiants, Motif motif, Nature nature,
			Semestre semestre, SemestreLmd semestreLmd, Date dateSaisie, Date dateAbsence) {
		this.codeAbsence = codeAbsence;
		this.anneesScolaire = anneesScolaire;
		this.etudiants = etudiants;
		this.motif = motif;
		this.nature = nature;
		this.semestre = semestre;
		this.semestreLmd = semestreLmd;
		this.dateSaisie = dateSaisie;
		this.dateAbsence = dateAbsence;
	}

	@Id

	@Column(name = "CODE_ABSENCE", unique = true, nullable = false)
	public int getCodeAbsence() {
		return this.codeAbsence;
	}

	public void setCodeAbsence(int codeAbsence) {
		this.codeAbsence = codeAbsence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ANNEES", nullable = false)
	public AnneesScolaire getAnneesScolaire() {
		return this.anneesScolaire;
	}

	public void setAnneesScolaire(AnneesScolaire anneesScolaire) {
		this.anneesScolaire = anneesScolaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUMETUDIANT", nullable = false)
	public Etudiants getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Etudiants etudiants) {
		this.etudiants = etudiants;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_MOTIF", nullable = false)
	public Motif getMotif() {
		return this.motif;
	}

	public void setMotif(Motif motif) {
		this.motif = motif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_NATURE", nullable = false)
	public Nature getNature() {
		return this.nature;
	}

	public void setNature(Nature nature) {
		this.nature = nature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_SEMESTRE")
	public Semestre getSemestre() {
		return this.semestre;
	}

	public void setSemestre(Semestre semestre) {
		this.semestre = semestre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_SEMESTRE_LMD")
	public SemestreLmd getSemestreLmd() {
		return this.semestreLmd;
	}

	public void setSemestreLmd(SemestreLmd semestreLmd) {
		this.semestreLmd = semestreLmd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_SAISIE", length = 10)
	public Date getDateSaisie() {
		return this.dateSaisie;
	}

	public void setDateSaisie(Date dateSaisie) {
		this.dateSaisie = dateSaisie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ABSENCE", length = 10)
	public Date getDateAbsence() {
		return this.dateAbsence;
	}

	public void setDateAbsence(Date dateAbsence) {
		this.dateAbsence = dateAbsence;
	}

}
